"""bigint

Revision ID: 14de3a5684ea
Revises: bd42bc6088a1
Create Date: 2023-02-22 21:30:21.156049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14de3a5684ea'
down_revision = 'bd42bc6088a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE tg_user ALTER COLUMN tg_id TYPE bigint USING tg_id::bigint;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM "tg_user" WHERE tg_id>2147483648 OR tg_id<-2147483647;')
    op.execute('ALTER TABLE "tg_user" ALTER COLUMN tg_id TYPE int USING tg_id::int;')
    # ### end Alembic commands ###