"""Init

Revision ID: 56584d8792af
Revises: 
Create Date: 2023-01-12 18:59:05.426265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56584d8792af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_user',
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tg_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tg_user')
    # ### end Alembic commands ###